### ISSUE TITLE
Datastore.KEY error with TypeScript in 6.4.0 (updating from 6.3.1)

### ISSUE THREAD

**Issue by vicb** [googleapis/nodejs-datastore#830]
#### Environment details

  - OS: MacOS
  - Node.js version: v14.15.5
  - npm version: 7.13.0
  - `@google-cloud/datastore` version: 6.4.0

#### Steps to reproduce

After updating my `@google-cloud/datastore` dep from 6.3.1 to 6.4.0 I get a build error:

```
(!) Plugin typescript: @rollup/plugin-typescript TS2345: Argument of type 'TrackerForUpdate' is not assignable to parameter of type '{ [KEY_SYMBOL]: Key; }'.
  Property '[Datastore.KEY]' is missing in type 'TrackerForUpdate' but required in type '{ [KEY_SYMBOL]: Key; }'.

[...]

(!) Plugin typescript: @rollup/plugin-typescript TS2551: Property '__@KEY_SYMBOL@163521' does not exist on type 'LiveTrackEntity'. Did you mean '__@KEY_SYMBOL@160080'?
```

I use rollup to build my project.

I'll investigate the issue and add more details here as I progress.

I am just creating the issue now if somebody already hit the issue.

[6.3.1 vs 6.4.0](https://github.com/googleapis/nodejs-datastore/compare/v6.3.1...v6.4.0)

edit: I don't see any obvious thing in the source code changes... I'll look at the generated package (from npm) next.

**Comment by vicb** [comment]
It seems like the issue was that my project somehow ended up with two versions of the `@google-cloud/datastore` package. 

It explained why `KEY_SYMBOL` was different across the versions.

I fixed that by making sure the project only uses a single version of the package.
